'use client';
import Navbar from '@components/Navbar';
import Topbar from '@components/Topbar';
import '@styles/globals.css';
import { useState, useEffect, useContext } from 'react';

export const metadata = {
	title: '90 Minutes Madness',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const [theme, setTheme] = useState('');

	useEffect(() => {
		if (!('theme' in localStorage)) {
			const sysTheme = window.matchMedia(
				'(prefers-color-scheme: dark)'
			).matches;
			if (!sysTheme) {
				setTheme('light');
			} else {
				setTheme('dark');
			}
		} else {
			setTheme(localStorage.getItem('theme'));
			console.log(theme);
		}
	}, [theme]);

	return (
		<html
			lang="en"
			className={theme}>
			<body
				className="w-screen min-h-screen bg-primary-bg dark:bg-dark-primary-bg"
				suppressHydrationWarning={true}>
				<div className="container relative">
					<Topbar
						theme={theme}
						setTheme={setTheme}
					/>
					<Navbar />
					{children}
				</div>
			</body>
		</html>
	);
}
