import Navbar from '@components/Navbar';
import '@styles/globals.css';

export const metadata = {
	title: '90 Minutes Madness',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className="">
			<body
				className="w-full min-h-full bg-primary-bg dark:bg-dark-primary-bg"
				suppressHydrationWarning={true}>
				<div className="container relative">
					<Navbar />
					{children}
				</div>
			</body>
		</html>
	);
}
