'use client';
import Navbar from '@components/Navbar';
import Topbar from '@components/Topbar';
import { ThemeContextProvider } from '@contexts/themeContext';
import '@styles/globals.css';
import { useState, useEffect } from 'react';

export const metadata = {
	title: '90 Minutes Madness',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const [theme, setTheme] = useState();
	useEffect(() => {
		if (
			localStorage.theme === 'dark' ||
			(!('theme' in localStorage) &&
				window.matchMedia('(prefers-color-scheme: dark)').matches)
		) {
			setTheme('dark');
		} else {
			setTheme('');
		}
	}, [theme]);

	console.log(theme);
	return (
		<html
			lang="en"
			className={theme}>
			<body
				className="w-screen min-h-screen bg-primary-bg dark:bg-dark-primary-bg"
				suppressHydrationWarning={true}>
				<ThemeContextProvider>
					<div className="container relative">
						<Topbar />
						<Navbar />
						{children}
					</div>
				</ThemeContextProvider>
			</body>
		</html>
	);
}
